### ISSUE TITLE
Fix Jupyter Notebook stats

### ISSUE THREAD

**Issue by sneakers-the-rat** [hsw28/ca_imaging#1]
hello! (this is jonny from neuromatch.social)

So i installed `linguist` locally and ran it with the `--breakdown` option, and it says that the file that's being detected as Jupyter notebook is `dim_reduction/annotated_MIND/mind_demo.ipynb` which is ~3k lines long. Interestingly it seems like those statistics are counted *per character* rather than per line, which is why the jupyter notebook swamps everything else (images are base64 encoded, and so are a bazillion and a half characters)

Currently the `.gitattributes` file is: https://github.com/hsw28/ca_imaging/blob/3009b642e18492d76345968647961ddb814e3118/.gitattributes#L1

but that's not using `linguist`'s ignore syntax, see: https://github.com/github-linguist/linguist/blob/master/docs/overrides.md

Testing locally, when I change `.gitattributes` to:

```
*.ipynb -linguist-detectable
```

(and then commit that file, linguist doesn't use the .gitattributes file until it's committed) then I get the correct stats

```bash
$ github-linguist
77.76%  1703444    MATLAB
14.70%  322036     C++
2.27%   49644      C
2.23%   48802      Python
1.30%   28379      HTML
0.95%   20824      Shell
0.53%   11706      M
0.17%   3675       PowerShell
0.09%   1954       Rich Text Format
0.00%   85         Mercury
```

**Comment by hsw28** [comment]
IT WORKED!!! THANK YOU!!!

still dont understand why when i would click jupyter on the github repo it would say no code matched it, but you know, i'm good with the mystery

**Comment by sneakers-the-rat** [comment]
I think that's one of the [search limitations](https://docs.github.com/en/search-github/github-code-search/about-github-code-search#limitations) they mention - since the file is 1.5MB, it isn't indexed in search. but hey, a lil mystery is good now and then <3
